export const events = [
    {
      id: "1",
      title: "Students Day",
      date: new Date(2030, 4, 2),
      type: "social",
    },
    {
      id: "2",
      title: "Teacher Pro...",
      date: new Date(2030, 4, 2),
      type: "meeting",
    },
    {
      id: "3",
      title: "AP Calculus...",
      date: new Date(2030, 4, 2),
      type: "academic",
    },
    {
      id: "4",
      title: "Spring Conc...",
      date: new Date(2030, 4, 2),
      type: "activity",
    },
    {
      id: "5",
      title: "Cinco de Ma...",
      date: new Date(2030, 4, 5),
      type: "social",
    },
    {
      id: "6",
      title: "Science Fair...",
      date: new Date(2030, 4, 8),
      type: "academic",
    },
    {
      id: "7",
      title: "Teacher Mee...",
      date: new Date(2030, 4, 8),
      type: "meeting",
    },
    {
      id: "8",
      title: "PTA Meeting",
      date: new Date(2030, 4, 9),
      type: "meeting",
    },
    {
      id: "9",
      title: "English Liter...",
      date: new Date(2030, 4, 13),
      type: "academic",
    },
    {
      id: "10",
      title: "Varsity Trac...",
      date: new Date(2030, 4, 15),
      type: "activity",
    },
    {
      id: "11",
      title: "Junior Prom",
      date: new Date(2030, 4, 16),
      type: "social",
    },
    {
      id: "12",
      title: "Senior Proje...",
      date: new Date(2030, 4, 19),
      type: "academic",
    },
    {
      id: "13",
      title: "Teacher Mee...",
      date: new Date(2030, 4, 19),
      type: "meeting",
    },
    {
      id: "14",
      title: "Board of Edu...",
      date: new Date(2030, 4, 21),
      type: "meeting",
    },
    {
      id: "15",
      title: "Art Exhibitio...",
      date: new Date(2030, 4, 22),
      type: "activity",
    },
    {
      id: "16",
      title: "Drama Club...",
      date: new Date(2030, 4, 23),
      type: "activity",
    },
    {
      id: "17",
      title: "PTA Meeting",
      date: new Date(2030, 4, 23),
      type: "meeting",
    },
    {
      id: "18",
      title: "Memorial D...",
      date: new Date(2030, 4, 26),
      type: "social",
    },
    {
      id: "19",
      title: "Sophomore ...",
      date: new Date(2030, 4, 28),
      type: "academic",
    },
    {
      id: "20",
      title: "Art Fair & Ex...",
      date: new Date(2030, 4, 28),
      type: "activity",
    },
    {
      id: "21",
      title: "Last Day of S...",
      date: new Date(2030, 4, 30),
      type: "social",
    },
  ];