export const categories = [
  {
    _id: "673ed96f627506753b4c273c",
    categoryName: "Advanced Placement (AP) Courses",
    subCategories: [],
    description:
      "Offers college-level curricula and exams to high school students.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "inactive",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T13:21:54.218Z",
  },
  {
    _id: "673ed96f627506753b4c273b",
    categoryName: "Test Prep Courses",
    subCategories: [],
    description:
      "Preparing students for college entrance exams such as SAT and ACT.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "inactive",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T13:05:15.480Z",
  },
  {
    _id: "673ed96f627506753b4c273a",
    categoryName: "Music and Dance Courses",
    subCategories: [],
    description:
      "Nurtures creativity and expression through musical instruments, vocal training, and dance.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "inactive",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T13:16:58.229Z",
  },
  {
    _id: "673ed96f627506753b4c2739",
    categoryName: "Sports and Fitness Courses",
    subCategories: [],
    description:
      "Encourages physical fitness, teamwork, and sportsmanship through diverse activities.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "inactive",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T13:17:04.171Z",
  },
  {
    _id: "673ed96f627506753b4c2738",
    categoryName: "Teen Leadership & Mentoring Courses",
    subCategories: [],
    description:
      "Focuses on developing leadership skills in teenagers and providing mentoring opportunities.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "inactive",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T13:21:57.765Z",
  },
  {
    _id: "673ed96f627506753b4c2737",
    categoryName: "Religion Courses",
    subCategories: [],
    description:
      "Focuses on educating students about world religions and ethics.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2736",
    categoryName: "Foreign Language Courses",
    subCategories: [],
    description:
      "Helps students acquire proficiency in languages like Spanish, French, and Mandarin.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2735",
    categoryName: "Kids Coding & Robotics Courses",
    subCategories: [],
    description:
      "Focused on teaching coding and robotics to students from kindergarten to 12th grade.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2734",
    categoryName: "Social Studies Courses",
    subCategories: [],
    description:
      "Covers history, geography, and civics to build students’ understanding of the world.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2733",
    categoryName: "Tutors & Teachers Training Courses",
    subCategories: [],
    description:
      "Focused on equipping tutors and teachers with the skills and strategies they need for effective instruction.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2732",
    categoryName: "K12 Courses",
    subCategories: [],
    description:
      "A comprehensive learning path designed for students from 3rd grade to 12th grade.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 0,
    regularCourse: 0,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2731",
    categoryName: "12th Grade Courses",
    subCategories: [],
    description:
      "A capstone year focusing on college prep, advanced calculus, physics, and literature.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 10,
    regularCourse: 14,
    totalCourse: 12,
    studentNumber: 120,
    tutorNumber: 14,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2730",
    categoryName: "11th Grade Courses",
    subCategories: [],
    description:
      "Prepares students for college with further specialization in math, science, and humanities.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 9,
    regularCourse: 13,
    totalCourse: 11,
    studentNumber: 110,
    tutorNumber: 13,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c272f",
    categoryName: "10th Grade Courses",
    subCategories: [],
    description:
      "Advanced courses in geometry, chemistry, and world history to prepare for standardized tests.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 8,
    regularCourse: 12,
    totalCourse: 10,
    studentNumber: 100,
    tutorNumber: 12,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c272e",
    categoryName: "9th Grade Courses",
    subCategories: [],
    description:
      "Focuses on algebra, biology, and foundational literature studies for high school success.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 7,
    regularCourse: 11,
    totalCourse: 9,
    studentNumber: 90,
    tutorNumber: 11,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c272d",
    categoryName: "8th Grade Courses",
    subCategories: [],
    description:
      "Prepares students for high school with advanced math, science, and U.S. history.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 6,
    regularCourse: 10,
    totalCourse: 8,
    studentNumber: 80,
    tutorNumber: 10,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c272c",
    categoryName: "7th Grade Courses",
    subCategories: [],
    description:
      "Emphasizes critical thinking with a focus on life sciences and algebra.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 5,
    regularCourse: 9,
    totalCourse: 7,
    studentNumber: 70,
    tutorNumber: 9,
    status: "activ",
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c272b",
    categoryName: "6th Grade Courses",
    subCategories: [],
    description:
      "Introduction to middle school, covering advanced math, reading, and earth science.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 4,
    regularCourse: 8,
    totalCourse: 6,
    studentNumber: 60,
    tutorNumber: 8,
    status: "activ",
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c272a",
    categoryName: "5th Grade Courses",
    subCategories: [],
    description:
      "Prepares students for the middle school transition with intermediate skills in math, science, and language arts.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 3,
    regularCourse: 7,
    totalCourse: 5,
    studentNumber: 50,
    tutorNumber: 7,
    status: "activ",
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2729",
    categoryName: "4th Grade Courses",
    subCategories: ["Arithmetic", "Reading", "Science"],
    description:
      "Adds complexity in reading comprehension and problem-solving in math.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 2,
    regularCourse: 6,
    totalCourse: 4,
    studentNumber: 40,
    tutorNumber: 6,
    status: "activ",
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2728",
    categoryName: "3rd Grade Courses",
    subCategories: ["Arithmetic", "Reading", "Science"],
    description:
      "Focused on foundational learning in arithmetic, reading, and science.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 1,
    regularCourse: 5,
    totalCourse: 3,
    studentNumber: 30,
    tutorNumber: 5,
    status: "activ",
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2727",
    categoryName: "Elementary School Courses",
    subCategories: ["C#"],
    description:
      "Focused on building foundational skills for 3rd to 5th graders in core subjects.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 3,
    regularCourse: 8,
    totalCourse: 5,
    studentNumber: 60,
    tutorNumber: 10,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2726",
    categoryName: "C#",
    subCategories: ["C#"],
    description: "oop",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 1,
    regularCourse: 1,
    totalCourse: 1,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2725",
    categoryName: " Science",
    subCategories: ["Biology", "Chemistry", "Physics", "Earth Sciences"],
    description:
      "Explore the wonders of science through engaging lessons in biology, chemistry, physics, and earth sciences. This course provides a solid foundation in scientific concepts and encourages critical thinking and experimentation. Perfect for students looking to understand the world around them.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 9,
    regularCourse: 9,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2724",
    categoryName: "Test Prep Courses for College Entrance",
    subCategories: ["SAT", "ACT", "Other College Entrance Exams"],
    description:
      "ScholarPASS's Test Prep Program helps students excel in SAT, ACT, and other college entrance exams. Offering personalized tutoring, practice tests, and expert guidance, it focuses on mastering content, test-taking strategies, and stress management. The program adapts to each student's needs, maximizing their potential for high scores and successful college admissions.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 8,
    regularCourse: 9,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2723",
    categoryName: " Maths",
    subCategories: ["Arithmetic", "Algebra", "Geometry", "Calculus"],
    description:
      "ScholarPASS's Math Program helps 3rd to 12th graders build a strong math foundation. Covering arithmetic to calculus, it offers personalized tutoring, interactive modules, and hands-on activities. The program fosters critical thinking, logical reasoning, and a love for math, preparing students for academic challenges and lifelong success.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 5,
    regularCourse: 8,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2722",
    categoryName: "English Language Arts",
    subCategories: ["Reading", "Writing", "Communication"],
    description:
      "ScholarPASS's English Language Arts (ELA) Program helps 3rd to 12th graders develop strong reading, writing, and communication skills. With personalized tutoring and interactive activities, students build a deep understanding of language and learn to express themselves clearly, preparing for success in academics and beyond.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 12,
    regularCourse: 8,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2721",
    categoryName: "Art ",
    subCategories: ["Drawing", "Painting", "Sculpture", "Digital Art"],
    description:
      "ScholarPASS's Art Program nurtures creativity in 3rd to 12th graders, offering personalized instruction in drawing, painting, sculpture, and digital art. It builds artistic skills, creative confidence, and visual literacy, providing a supportive space for students to explore and express their unique artistic voice.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 3,
    regularCourse: 8,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2720",
    categoryName: "Coding & Robotics",
    subCategories: ["C", "Python", "Java"],
    description:
      "ScholarPASS's Teens Coding & Robotics Program teaches 13 to 19-year-olds essential tech skills through hands-on projects in coding, robotics, and AI. It prepares teens for future tech careers and advanced projects.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 5,
    regularCourse: 6,
    totalCourse: 0,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c271f",
    categoryName: "Bootcamp",
    subCategories: ["C", "C#", "C++"],
    description:
      "An intensive, fast-paced course designed to equip students with comprehensive knowledge and hands-on skills in a specific subject or field, focusing on practical learning and real-world application in a condensed time frame.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 3,
    regularCourse: 4,
    totalCourse: 1,
    studentNumber: 0,
    tutorNumber: 0,
    status: "active",
    isFeatured: false,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c271e",
    categoryName: "Business Studies",
    subCategories: ["Marketing", "Management", "Finance"],
    description:
      "Explore the world of business and learn strategies for success.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 5,
    regularCourse: 7,
    totalCourse: 12,
    studentNumber: 160,
    tutorNumber: 12,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c271d",
    categoryName: "Art & Design",
    subCategories: ["Graphic Design", "Painting", "Photography"],
    description:
      "Show creativity and master artistic skills through hands-on projects.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 4,
    regularCourse: 6,
    totalCourse: 10,
    studentNumber: 110,
    tutorNumber: 9,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c271c",
    categoryName: "Economics",
    subCategories: ["Microeconomics", "Macroeconomics", "Game Theory"],
    description: "Understand markets and economies to make informed decisions.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 3,
    regularCourse: 5,
    totalCourse: 8,
    studentNumber: 90,
    tutorNumber: 8,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c271b",
    categoryName: "Physics",
    subCategories: ["Mechanics", "Optics", "Thermodynamics"],
    description:
      "Explore the laws of nature and their real-world applications.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 4,
    regularCourse: 9,
    totalCourse: 13,
    studentNumber: 140,
    tutorNumber: 11,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c271a",
    categoryName: "Chemistry",
    subCategories: ["Organic Chemistry", "Inorganic Chemistry", "Biochemistry"],
    description:
      "Understand the elements and chemical reactions that shape the world.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 3,
    regularCourse: 7,
    totalCourse: 10,
    studentNumber: 130,
    tutorNumber: 10,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
  {
    _id: "673ed96f627506753b4c2719",
    categoryName: "Biology",
    subCategories: ["Botany", "Zoology", "Genetics"],
    description:
      "Discover the fascinating world of life sciences and understand how living things work.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 4,
    regularCourse: 9,
    totalCourse: 13,
    studentNumber: 180,
    tutorNumber: 14,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T11:27:29.784Z",
  },
  {
    _id: "673ed96f627506753b4c2718",
    categoryName: "Test Prep",
    subCategories: ["SAT", "ACT", "GRE"],
    description:
      "Ace your exams with in-depth preparation and test-taking strategies.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 3,
    regularCourse: 6,
    totalCourse: 9,
    studentNumber: 120,
    tutorNumber: 10,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T11:27:27.712Z",
  },
  {
    _id: "673ed96f627506753b4c2717",
    categoryName: "English",
    subCategories: ["Grammar", "Literature", "Writing"],
    description:
      "Enhance your language skills and master the art of communication.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 6,
    regularCourse: 10,
    totalCourse: 16,
    studentNumber: 300,
    tutorNumber: 20,
    status: "inactive",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T11:27:51.847Z",
  },
  {
    _id: "673ed96f627506753b4c2716",
    categoryName: "Science",
    subCategories: ["Physics", "Chemistry", "Astronomy"],
    description:
      "Unlock the secrets of the universe with a comprehensive understanding of scientific principles.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 4,
    regularCourse: 8,
    totalCourse: 12,
    studentNumber: 150,
    tutorNumber: 12,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-25T11:00:36.814Z",
  },
  {
    _id: "673ed96f627506753b4c2715",
    categoryName: "Mathematics",
    subCategories: ["Algebra", "Geometry", "Calculus"],
    description:
      "Master the numbers and develop analytical skills through engaging lessons in mathematical concepts.",
    image: "https://placehold.co/600x600.png",
    bootCampCourse: 5,
    regularCourse: 10,
    totalCourse: 15,
    studentNumber: 200,
    tutorNumber: 15,
    status: "active",
    isFeatured: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    updatedAt: "2024-11-20T00:00:00.000Z",
  },
];
export const courses = [
  {
    seoTags: {
      seoMetadata: "",
      seoDescription: "",
    },
    _id: "6740717286472b29df29ad8e",
    title: "Expedita dicta non q",
    short_description: "Aut sapiente recusan",
    description: "Amet fugit dolores",
    thumbnail:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1732276590/h0a8zehfjhnwsxren6ew.png",
    overview_video: "Laboris quibusdam ap",
    course_type: "66deaf3e12a61e132071ac73",
    category: {
      _id: "673ed96f627506753b4c273b",
      categoryName: "Test Prep Courses",
    },
    subCategory: "",
    price: 16,
    discount: 0,
    duration: "Aute consequatur sin",
    instructor: {
      _id: "67406f4686472b29df29acdc",
      name: "Orla Crane",
      image: "",
      profession: "",
      about: "",
    },
    level: "beginner",
    language: "Minus quis qui labor",
    totalSeat: 63,
    enrolledStudents: [],
    requirements: ["Quibusdam aperiam pr"],
    outcomes: ["Exercitationem nisi "],
    courseTags: [],
    expiringMonth: null,
    cetification: false,
    courseIncludes: ["Aut incidunt aspern"],
    courseBadge: "new",
    status: "pending",
    isBootcamp: false,
    createdAt: "2024-11-22T11:56:34.573Z",
    updatedAt: "2024-11-22T11:56:34.573Z",
    totalReviews: 0,
    averageRating: 0,
  },
  {
    seoTags: {
      seoMetadata: "",
      seoDescription: "",
    },
    _id: "673dcddd00de8f37be15d1e2",
    title: "Magna in et aut dolo",
    short_description: "Minim laborum qui vo",
    description: "Quaerat adipisicing ",
    thumbnail:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1732103641/b7nd40kwkhzhwa7atq2m.png",
    overview_video: "Quasi sunt nulla ips",
    course_type: "66deaf3e12a61e132071ac73",
    category: {
      _id: "673ed96f627506753b4c2715",
      categoryName: "Mathematics",
    },
    subCategory: "",
    price: 669,
    discount: 0,
    duration: "Temporibus deserunt ",
    instructor: {
      _id: "673c50073f1c8c7578c79517",
      name: "Hilel Kent",
      image:
        "https://res.cloudinary.com/dsy2erizv/image/upload/v1732005892/xpasgdoamm6mbjfhm3dp.png",
      profession: "Tempore fugiat atq",
      about: "Error quam dolor eni",
    },
    level: "beginner",
    language: "Aspernatur amet nul",
    totalSeat: 95,
    enrolledStudents: [],
    requirements: ["Rem voluptas nihil s"],
    outcomes: ["Rerum illo ipsam off"],
    courseTags: ["tag"],
    expiringMonth: null,
    cetification: false,
    courseIncludes: ["Rerum elit est quia"],
    courseBadge: "new",
    status: "pending",
    isBootcamp: true,
    createdAt: "2024-11-20T11:54:05.198Z",
    updatedAt: "2024-11-22T11:22:50.980Z",
    totalReviews: 0,
    averageRating: 0,
  },
  {
    seoTags: {
      seoMetadata: "",
      seoDescription: "",
    },
    isBootcamp: false,
    _id: "6735ac48918dee6115f62833",
    title: "Vitae consequat Dol",
    short_description: "Provident quidem po",
    description: "Ducimus in similiqu",
    thumbnail:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1731570736/mh2hyrrm0dwn1ucrprim.png",
    overview_video: "Fugiat doloremque qu",
    course_type: "66deaf4512a61e132071ac78",
    category: null,
    subCategory: "food",
    price: 330,
    discount: 0,
    duration: "Eum quasi excepteur ",
    instructor: {
      _id: "67348c3b6248ff1829d81057",
      name: "Sophia Griffith",
      image:
        "https://res.cloudinary.com/dsy2erizv/image/upload/v1731497007/bcgk5hpqw7tikf8jkfez.png",
      profession: "Voluptatibus omnis p",
      about: "Nostrum vel totam en",
    },
    level: "beginner",
    language: "Autem incidunt recu",
    totalSeat: 93,
    enrolledStudents: [],
    requirements: ["Id error est digniss"],
    outcomes: ["Est adipisci sed ten"],
    courseTags: [],
    expiringMonth: null,
    cetification: false,
    courseIncludes: ["Fugiat sunt sunt off"],
    courseBadge: "new",
    status: "pending",
    createdAt: "2024-11-14T07:52:40.532Z",
    updatedAt: "2024-11-14T07:52:40.532Z",
    totalReviews: 0,
    averageRating: 0,
  },
  {
    seoTags: {
      seoMetadata: "",
      seoDescription: "",
    },
    isBootcamp: false,
    _id: "672a09453e6dccbd9945e42c",
    title: "SQA",
    short_description: "sqas qsa sqa",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
    thumbnail:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1730808124/p5nzsc32dgvzb0a5vi8k.jpg",
    overview_video:
      "https://www.youtube.com/watch?v=wDCZiq-d_PQ&list=PLptLP7KjDoqVNLwIJVlkyi85XIlE7Y9WD",
    course_type: "66deaf3e12a61e132071ac73",
    category: null,
    subCategory: "JavaScript",
    price: 60,
    discount: 0,
    duration: "4 hour",
    instructor: {
      _id: "67077edd00a4ff8cd1ab4d6d",
      name: "Mainul",
      image:
        "https://res.cloudinary.com/dsy2erizv/image/upload/v1731220642/cwmgohc6t2ocmmuheo0c.png",
      profession: "Software Developer",
      about: "I am a good Software developer",
    },
    level: "advanced",
    language: "English",
    totalSeat: 50,
    enrolledStudents: [],
    requirements: ["Lorem ipsum", " dolor sit ame"],
    outcomes: ["consectetur adipiscing elit", "Sed do eiusmod "],
    courseTags: ["sqa", "web"],
    expiringMonth: null,
    cetification: true,
    courseIncludes: [
      "tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
    ],
    courseBadge: "new",
    status: "pending",
    createdAt: "2024-11-05T12:02:13.764Z",
    updatedAt: "2024-11-05T12:02:13.764Z",
    totalReviews: 5,
    averageRating: 4.4,
  },
  {
    seoTags: {
      seoMetadata: "",
      seoDescription: "",
    },
    isBootcamp: false,
    _id: "6714d6bc4a27f8ec6ba8da66",
    title: "Flutter Intermideate",
    short_description:
      "\r\nThe Flutter Intermediate Course covers state management (Provider, GetX), advanced UI concepts (animations, custom widgets), and API integration. You'll also learn Firebase setup, navigation, testing, and deploying apps on app stores. This course is ideal for developers looking to enhance their skills and build scalable, production-ready Flutter apps.",
    description:
      "Flutter Intermediate Course Outline\r\nModule 1: Intermediate Dart Concepts\r\nRecap of Dart Basics:\r\nVariables, Data Types, Functions\r\nCollections and Maps:\r\nAdvanced usage of Lists, Sets, and Maps\r\nSorting, filtering, and transforming collections\r\nAsynchronous Programming:\r\nFutures, Async-Await\r\nStream API, handling real-time data streams\r\nError Handling:\r\nCustom exceptions\r\nDebugging and logging techniques\r\nModule 2: State Management in Flutter\r\nUnderstanding State:\r\nLocal vs Global state\r\nEphemeral and App State\r\nProvider Package:\r\nIntro to Provider, ChangeNotifier\r\nCreating and using Providers effectively\r\nGetX:\r\nIntroduction to GetX for State Management\r\nUsing Controllers, Observables, and Reactive Programming\r\nDependency Injection with GetX\r\nRiverpod:\r\nWhy Riverpod over Provider?\r\nUsing Riverpod for robust state management\r\nModule 3: Networking and API Integration\r\nDio vs Http:\r\nFetching Data from APIs\r\nHandling GET, POST, PUT, DELETE requests\r\nJSON Parsing:\r\nWorking with JSON data\r\nModel classes, fromJson, toJson\r\nHandling Errors:\r\nManaging API errors and retries\r\nPagination and Infinite Scroll:\r\nBuilding dynamic lists with paginated data\r\nSecure API Calls:\r\nStoring and sending sensitive data securely\r\nModule 4: Advanced UI Concepts\r\nAnimations:\r\nImplicit vs Explicit Animations\r\nCustom animations using Tween, AnimationController, Hero animations\r\nCustom Widgets:\r\nCreating reusable custom widgets\r\nUsing SliverList, SliverGrid, and CustomScrollView for advanced layouts\r\nThemes and Custom Styling:\r\nTheming the app using ThemeData\r\nDark Mode support\r\nWorking with Forms:\r\nBuilding and validating complex forms\r\nManaging form input and validation logic\r\nModule 5: Navigation and Routing\r\nFlutter Navigator 2.0:\r\nDeclarative routing with Router and RouteInformationParser\r\nHandling deep links\r\nGetX Navigation:\r\nSimple and efficient navigation with GetX\r\nRoute guards and access control\r\nModule 6: Firebase Integration\r\nFirebase Authentication:\r\nEmail/Password, Google, and Facebook Sign-in\r\nCloud Firestore:\r\nReal-time data sync and querying Firestore data\r\nFirebase Storage:\r\nUploading and retrieving media files\r\nPush Notifications:\r\nSetting up Firebase Cloud Messaging (FCM)\r\nModule 7: Flutter Plugins and Packages\r\nUsing Popular Packages:\r\nImage Picker, File Picker, Shared Preferences\r\nIntegrating Payment Gateways:\r\nStripe, Razorpay, and PayPal\r\nLocation Services:\r\nUsing GPS, geolocation, and mapping with Google Maps\r\nPlatform Channels:\r\nBridging communication between Flutter and native Android/iOS code\r\nModule 8: App Architecture\r\nBuilding Scalable Apps:\r\nUnderstanding MVC, MVVM, and Clean Architecture\r\nService Layer pattern\r\nDependency Injection:\r\nUsing GetX and other tools for managing dependencies\r\nModularization:\r\nBreaking down apps into smaller, maintainable modules\r\nModule 9: Testing and Debugging\r\nUnit Testing:\r\nWriting unit tests for logic components\r\nMocking services\r\nWidget Testing:\r\nTesting UI components\r\nIntegration Testing:\r\nTesting complete app flows\r\nDebugging Techniques:\r\nUnderstanding Flutter's DevTools\r\nDebugging performance issues and memory leaks\r\nModule 10: Publishing and App Maintenance\r\nApp Deployment:\r\nConfiguring the app for release (Android/iOS)\r\nApp Store/Play Store requirements\r\nManaging app permissions\r\nContinuous Integration (CI/CD):\r\nSetting up CI/CD with tools like Codemagic or GitHub Actions\r\nHandling App Updates:\r\nVersion control and migrating old users\r\nBackward compatibility for new features\r\nLearning Outcomes\r\nGain a deeper understanding of state management techniques like Provider, GetX, and Riverpod.\r\nLearn how to integrate Firebase and handle authentication, database, and storage operations.\r\nDevelop skills to create responsive, animated, and custom UI components.\r\nBuild scalable, maintainable apps with modular architecture and testing.\r\nBe able to handle real-world challenges like API integrations, pagination, and app performance.\r\nPublish apps on the Play Store and App Store with proper configurations.\r\nProject Work\r\nIntermediate Project 1: Build an E-commerce app with product listings, cart, and order management.\r\nIntermediate Project 2: Create a Social Media app with authentication, profile management, and chat functionality.\r\n",
    thumbnail:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1729418935/ilaxgrhzb0rrs3c3gtui.webp",
    overview_video: "https://www.youtube.com/watch?v=8vSF_ws3wtE&t=3s",
    course_type: "66deaf3e12a61e132071ac73",
    category: null,
    subCategory: "Dart",
    price: 60,
    discount: 0,
    duration: "4 hour",
    instructor: {
      _id: "67077edd00a4ff8cd1ab4d6d",
      name: "Mainul",
      image:
        "https://res.cloudinary.com/dsy2erizv/image/upload/v1731220642/cwmgohc6t2ocmmuheo0c.png",
      profession: "Software Developer",
      about: "I am a good Software developer",
    },
    level: "intermediate",
    language: "English",
    totalSeat: 50,
    enrolledStudents: [],
    requirements: [
      "Basic knowledge of Flutter and Dart",
      "Experience with building simple Flutter apps",
      "Familiarity with API calls and JSON parsing",
      "Basic understanding of version control (Git)",
      "Understanding of state management concepts (setState, etc.)",
    ],
    outcomes: [
      "Proficient in managing app state using Provider, GetX, and Riverpod.",
      "Ability to integrate APIs and handle networking tasks efficiently.",
      "Create custom, responsive, and animated UI components.",
      "Implement Firebase features like authentication, Firestore, and push notifications.",
      "Develop modular and scalable app architecture.",
    ],
    courseTags: ["flutter", "dart", "firebase"],
    expiringMonth: null,
    cetification: true,
    courseIncludes: [
      "In-depth lessons on state management (Provider, GetX, Riverpod)",
      "Advanced UI development (custom widgets, animations, responsive design)",
      "API integration (Dio, HTTP, JSON parsing)",
      "Firebase integration (Authentication, Firestore, Cloud Messaging)",
      "Navigation and routing (Flutter Navigator 2.0, GetX)",
    ],
    courseBadge: "new",
    status: "pending",
    createdAt: "2024-10-20T10:09:00.098Z",
    updatedAt: "2024-10-20T11:34:17.593Z",
    totalReviews: 1,
    averageRating: 4.5,
  },
  {
    seoTags: {
      seoMetadata: "",
      seoDescription: "",
    },
    isBootcamp: false,
    _id: "66dedeb98bbfda56cdd8457a",
    title: "React for Beginner ",
    short_description:
      "Sit sint dignissim Sit sint dignissim Sit sint dignissim",
    description:
      "Dolor irure id quis  Sit sint dignissim Sit sint dignissim Sit sint dignissim Dolor irure id quis  Sit sint dignissim Sit sint dignissim Sit sint dignissim Dolor irure id quis  Sit sint dignissim Sit sint dignissim Sit sint dignissim Dolor irure id quis  Sit sint dignissim Sit sint dignissim Sit sint dignissim Dolor irure id quis  Sit sint dignissim Sit sint dignissim Sit sint dignissim",
    thumbnail:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1725882037/oz4x4imuygwkh5w3g1ui.png",
    overview_video: "https://www.youtube.com/watch?v=srcDnsNyIJw",
    course_type: "66deaf4512a61e132071ac78",
    category: null,
    subCategory: "React",
    price: 499,
    discount: 0,
    duration: "3 hr 50 min",
    rating: 0,
    review: [],
    instructor: {
      _id: "66fe4cf099f24fdf90b17c38",
      name: "Jon",
      image:
        "https://i.pinimg.com/control/564x/a8/58/46/a858463ac4b8a4a6013ca80ed0e6c475.jpg",
      profession: "Flutter Developer",
      about: "I am a good flutter developer",
    },
    level: "advanced",
    language: "Voluptate ea velit u",
    totalSeat: 100,
    enrolledStudents: [],
    requirements: [
      "Repellendus Digniss",
      "Ea provident ea ad ",
      "Fuga Sunt necessit",
    ],
    outcomes: [
      "Illo odio porro temp",
      "Ipsa quod voluptate",
      "Rerum occaecat enim ",
      "Aliquip et temporibu",
    ],
    courseTags: [],
    expiringMonth: null,
    cetification: true,
    courseIncludes: [
      "Cumque aut modi volu",
      "Velit excepturi sin",
      "Dolorum ducimus eli",
      "Itaque pariatur In ",
      "Nulla in doloribus d",
    ],
    courseBadge: "new",
    status: "pending",
    createdAt: "2024-09-09T11:40:41.609Z",
    updatedAt: "2024-09-09T11:40:41.609Z",
    totalReviews: 8,
    averageRating: 3.19,
  },
];

export const tutors = [
  {
    _id: "6740649ec00ddbdc38a0244d",
    name: "Sayem",
    email: "sayem@khan.com",
    phone: "9034239023",
    image:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1732273290/msiqmhpsowwbpt26eigr.png",
    role: "instructor",
    profession: "dev",
    gender: null,
    about: "dev",
    country: null,
    expartise: ["fs", "js"],
    language: null,
    certificate: [],
    review: [],
    isVerified: false,
    authType: "manual",
    deviceToken: null,
    status: "active",
    createdAt: "2024-11-22T11:01:50.057Z",
    updatedAt: "2024-11-22T11:01:50.057Z",
  },
  {
    _id: "673c639620d25bbec0ab2bee",
    name: "Cassady Joyner",
    email: "zanemehol@mailinator.com",
    phone: "+1 (343) 318-8752",
    image:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1732010899/jbgfi2yfwos7fhxr0iku.png",
    role: "instructor",
    profession: "Adipisci consequuntu",
    gender: null,
    about: "Vel ut amet sint no",
    country: null,
    expartise: [],
    language: null,
    certificate: [],
    review: [],
    isVerified: false,
    authType: "manual",
    deviceToken: null,
    status: "active",
    createdAt: "2024-11-19T10:08:22.485Z",
    updatedAt: "2024-11-19T10:08:22.485Z",
  },
  {
    _id: "673c50073f1c8c7578c79517",
    name: "Hilel Kent",
    email: "zomalop@mailinator.com",
    phone: "+1 (503) 194-5476",
    image:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1732005892/xpasgdoamm6mbjfhm3dp.png",
    role: "instructor",
    profession: "Tempore fugiat atq",
    gender: null,
    about: "Error quam dolor eni",
    country: null,
    expartise: [],
    language: null,
    certificate: [],
    review: [],
    isVerified: false,
    authType: "manual",
    deviceToken: null,
    status: "active",
    createdAt: "2024-11-19T08:44:55.080Z",
    updatedAt: "2024-11-19T08:44:55.080Z",
  },
  {
    _id: "673c4fea3f1c8c7578c79513",
    name: "Eleanor Terrell",
    email: "cijuzycek@mailinator.com",
    phone: "+1 (281) 921-9694",
    image:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1732005862/t7vecfadqoacencsefwh.png",
    role: "instructor",
    profession: "Non adipisicing sed ",
    gender: null,
    about: "Repudiandae velit ip",
    country: null,
    expartise: [],
    language: null,
    certificate: [],
    review: [],
    isVerified: false,
    authType: "manual",
    deviceToken: null,
    status: "active",
    createdAt: "2024-11-19T08:44:26.252Z",
    updatedAt: "2024-11-19T08:44:26.252Z",
  },
  {
    _id: "673976b9f233fac6dce646ea",
    name: "Mainul",
    email: "test@mentor.com",
    phone: "1521226758",
    image:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1731819097/tcbwi67nea8yfcslthyp.jpg",
    role: "instructor",
    profession: "mentor",
    gender: null,
    about: "Siu",
    country: "Bangladesh",
    expartise: ["Flutter"],
    language: ["Bangla"],
    certificate: [],
    review: [],
    isVerified: false,
    authType: "manual",
    deviceToken: null,
    status: "active",
    createdAt: "2024-11-17T04:53:13.525Z",
    updatedAt: "2024-11-17T04:53:13.525Z",
  },
  {
    _id: "673884173efc6d7f466bb2c8",
    name: "Chase Gilmore",
    email: "quqisi@mailinator.com",
    phone: "+1 (816) 213-7372",
    image:
      "https://res.cloudinary.com/dsy2erizv/image/upload/v1731757077/v5mv10btzdrjdxr2ejhn.jpg",
    role: "instructor",
    profession: "Tempore porro nesci",
    gender: null,
    about: "Architecto aliquam v",
    country: null,
    expartise: [],
    language: null,
    certificate: [],
    review: [],
    isVerified: false,
    authType: "manual",
    deviceToken: null,
    status: "active",
    createdAt: "2024-11-16T11:37:59.983Z",
    updatedAt: "2024-11-16T11:37:59.983Z",
  },
];
